import { useState } from "react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { FormError } from "@/components/FormError";
import { cn } from "@/lib/utils";
import { parseTimeToMinutes } from "@/lib/scheduleTime";
import {
  ApiError,
  type AutoGenerateSchedulePayload,
  type ScheduleDistributionStrategy,
} from "@/api/client";

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onGenerate: (payload: AutoGenerateSchedulePayload) => Promise<void>;
}

export function AutoGenerateDialog({ open, onOpenChange, onGenerate }: AutoGenerateDialogProps) {
  const [startTime, setStartTime] = useState("08:00");
  const [lunchStartTime, setLunchStartTime] = useState("12:00");
  const [lunchDuration, setLunchDuration] = useState(60);
  const [warmupMinutes, setWarmupMinutes] = useState(10);
  const [distribution, setDistribution] = useState<ScheduleDistributionStrategy>("balanced");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function handleOpenChange(next: boolean) {
    if (!next) setError(null);
    onOpenChange(next);
  }

  async function handleSubmit() {
    setError(null);
    setLoading(true);
    try {
      await onGenerate({
        startMinutes: parseTimeToMinutes(startTime),
        lunchStartMinutes: parseTimeToMinutes(lunchStartTime),
        lunchDurationMinutes: lunchDuration,
        warmupMinutes,
        distribution,
      });
      handleOpenChange(false);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Erro inesperado. Tente novamente.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="gap-6 p-8 sm:max-w-lg">
        <div className="grid gap-1.5">
          <DialogTitle className="text-xl font-medium">Gerar cronograma automaticamente</DialogTitle>
          <DialogDescription>
            Preenche o dia inteiro a partir das apresentações ainda não agendadas, distribuindo
            entre as pistas.
          </DialogDescription>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-1.5">
            <Label>Horário inicial</Label>
            <input
              type="time"
              value={startTime}
              onChange={(e) => setStartTime(e.target.value)}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="grid gap-1.5">
            <Label>Duração do aquecimento (min)</Label>
            <input
              type="number"
              min={1}
              value={warmupMinutes}
              onChange={(e) => setWarmupMinutes(Number(e.target.value))}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="grid gap-1.5">
            <Label>Início do almoço</Label>
            <input
              type="time"
              value={lunchStartTime}
              onChange={(e) => setLunchStartTime(e.target.value)}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="grid gap-1.5">
            <Label>Duração do almoço (min)</Label>
            <input
              type="number"
              min={0}
              value={lunchDuration}
              onChange={(e) => setLunchDuration(Number(e.target.value))}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="col-span-2 grid gap-1.5">
            <Label>Distribuição entre pistas</Label>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setDistribution("balanced")}
                className={cn(
                  "flex-1 rounded-md border px-3 py-2 text-sm transition-colors",
                  distribution === "balanced"
                    ? "border-primary bg-primary/10 text-primary"
                    : "border-border/60 text-muted-foreground",
                )}
              >
                Balanceada
              </button>
              <button
                type="button"
                onClick={() => setDistribution("sequential")}
                className={cn(
                  "flex-1 rounded-md border px-3 py-2 text-sm transition-colors",
                  distribution === "sequential"
                    ? "border-primary bg-primary/10 text-primary"
                    : "border-border/60 text-muted-foreground",
                )}
              >
                Sequencial
              </button>
            </div>
          </div>
        </div>

        <FormError message={error} />

        <div className="flex justify-end gap-3">
          <Button variant="outline" onClick={() => handleOpenChange(false)} disabled={loading}>
            Cancelar
          </Button>
          <Button onClick={handleSubmit} disabled={loading}>
            {loading ? "Gerando..." : "Gerar cronograma"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
