import { useState } from "react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { FormError } from "@/components/FormError";
import { cn } from "@/lib/utils";
import { parseTimeToMinutes } from "@/lib/scheduleTime";
import {
  ApiError,
  type AutoGenerateSchedulePayload,
  type ScheduleDistributionStrategy,
} from "@/api/client";

interface AutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  // Intervalo padrão do dia (ScheduleDay.defaultGapMinutes) — mesmo
  // campo editável na barra de configurações do dia, só repetido aqui
  // pra não obrigar o usuário a ir noutro lugar antes de gerar (ver
  // `gapMinutes` no payload de `onGenerate`).
  initialGapMinutes: number;
  onGenerate: (payload: AutoGenerateSchedulePayload, gapMinutes: number) => Promise<void>;
}

export function AutoGenerateDialog({
  open,
  onOpenChange,
  initialGapMinutes,
  onGenerate,
}: AutoGenerateDialogProps) {
  const [startTime, setStartTime] = useState("08:00");
  const [lunchStartTime, setLunchStartTime] = useState("12:00");
  // Guardados como STRING, não number — bug real 2026-08-05: com state
  // number direto (`value={x}` + `onChange={(e) => setX(Number(e.target.value))}`),
  // apagar o campo pra digitar outro valor manda `e.target.value` vazio,
  // `Number("")` vira `0`, e o input imediatamente reexibe "0" antes do
  // usuário conseguir digitar — só dava pra trocar o valor digitando
  // ANTES de apagar o zero. String solta aceita campo vazio de verdade
  // enquanto digita; conversão pra number só acontece no submit (ver
  // handleSubmit), com fallback pro mínimo de cada campo se ficar
  // vazio/inválido.
  const [lunchDurationInput, setLunchDurationInput] = useState("60");
  const [warmupMinutesInput, setWarmupMinutesInput] = useState("10");
  const [gapMinutesInput, setGapMinutesInput] = useState(String(initialGapMinutes));
  const [distribution, setDistribution] = useState<ScheduleDistributionStrategy>("balanced");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function handleOpenChange(next: boolean) {
    if (next) setGapMinutesInput(String(initialGapMinutes));
    else setError(null);
    onOpenChange(next);
  }

  async function handleSubmit() {
    setError(null);
    setLoading(true);
    try {
      const warmupMinutes = Math.max(1, Number(warmupMinutesInput) || 0);
      const gapMinutes = Math.max(0, Number(gapMinutesInput) || 0);
      const lunchDuration = Math.max(0, Number(lunchDurationInput) || 0);
      await onGenerate(
        {
          startMinutes: parseTimeToMinutes(startTime),
          lunchStartMinutes: parseTimeToMinutes(lunchStartTime),
          lunchDurationMinutes: lunchDuration,
          warmupMinutes,
          distribution,
        },
        gapMinutes,
      );
      handleOpenChange(false);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Erro inesperado. Tente novamente.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="gap-6 p-8 sm:max-w-lg">
        <div className="grid gap-1.5">
          <DialogTitle className="text-xl font-medium">Gerar cronograma automaticamente</DialogTitle>
          <DialogDescription>
            Preenche o dia inteiro a partir das apresentações ainda não agendadas, distribuindo
            entre as pistas.
          </DialogDescription>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-1.5">
            <Label>Horário inicial</Label>
            <input
              type="time"
              value={startTime}
              onChange={(e) => setStartTime(e.target.value)}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="grid gap-1.5">
            <Label>Duração do aquecimento (min)</Label>
            <input
              type="number"
              min={1}
              value={warmupMinutesInput}
              onChange={(e) => setWarmupMinutesInput(e.target.value)}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="grid gap-1.5">
            <Label>Intervalo entre apresentações (min)</Label>
            <input
              type="number"
              min={0}
              value={gapMinutesInput}
              onChange={(e) => setGapMinutesInput(e.target.value)}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="grid gap-1.5">
            <Label>Início do almoço</Label>
            <input
              type="time"
              value={lunchStartTime}
              onChange={(e) => setLunchStartTime(e.target.value)}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="grid gap-1.5">
            <Label>Duração do almoço (min)</Label>
            <input
              type="number"
              min={0}
              value={lunchDurationInput}
              onChange={(e) => setLunchDurationInput(e.target.value)}
              className="rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
            />
          </div>
          <div className="col-span-2 grid gap-1.5">
            <Label>Distribuição entre pistas</Label>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => setDistribution("balanced")}
                className={cn(
                  "flex-1 rounded-md border px-3 py-2 text-sm transition-colors",
                  distribution === "balanced"
                    ? "border-primary bg-primary/10 text-primary"
                    : "border-border/60 text-muted-foreground",
                )}
              >
                Balanceada
              </button>
              <button
                type="button"
                onClick={() => setDistribution("sequential")}
                className={cn(
                  "flex-1 rounded-md border px-3 py-2 text-sm transition-colors",
                  distribution === "sequential"
                    ? "border-primary bg-primary/10 text-primary"
                    : "border-border/60 text-muted-foreground",
                )}
              >
                Sequencial
              </button>
            </div>
          </div>
        </div>

        <FormError message={error} />

        <div className="flex justify-end gap-3">
          <Button variant="outline" onClick={() => handleOpenChange(false)} disabled={loading}>
            Cancelar
          </Button>
          <Button onClick={handleSubmit} disabled={loading}>
            {loading ? "Gerando..." : "Gerar cronograma"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
