import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { FormError } from "@/components/FormError";
import { parseTimeToMinutes } from "@/lib/scheduleTime";
import { AutoGenerateOrderFields } from "@/components/AutoGenerateOrderFields";
import { SpecialEventsEditor } from "@/components/SpecialEventsEditor";
import { findSpecialEventsFormProblem } from "@/lib/specialEvents";
import {
  eventFormatKeysInDefaultOrder,
  mergeSavedFormatOrder,
} from "@/lib/autoFormatKey";
import {
  ApiError,
  categoriesApi,
  scheduleApi,
  type AutoGenerateLevelDirection,
  type AutoGenerateOrderPrimary,
  type AutoGenerateSchedulePayload,
  type Category,
  type SpecialEvent,
} from "@/api/client";

interface AutoGenerateDialogProps {
  eventId: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  // Intervalo padrão do dia (ScheduleDay.defaultGapMinutes) — mesmo
  // campo editável na barra de configurações do dia, só repetido aqui
  // pra não obrigar o usuário a ir noutro lugar antes de gerar (ver
  // `gapMinutes` no payload de `onGenerate`).
  initialGapMinutes: number;
  onGenerate: (
    payload: AutoGenerateSchedulePayload,
    gapMinutes: number,
  ) => Promise<void>;
}

export function AutoGenerateDialog({
  eventId,
  open,
  onOpenChange,
  initialGapMinutes,
  onGenerate,
}: AutoGenerateDialogProps) {
  const [startTime, setStartTime] = useState("08:00");
  // Guardados como STRING, não number — bug real 2026-08-05: com state
  // number direto (`value={x}` + `onChange={(e) => setX(Number(e.target.value))}`),
  // apagar o campo pra digitar outro valor manda `e.target.value` vazio,
  // `Number("")` vira `0`, e o input imediatamente reexibe "0" antes do
  // usuário conseguir digitar — só dava pra trocar o valor digitando
  // ANTES de apagar o zero. String solta aceita campo vazio de verdade
  // enquanto digita; conversão pra number só acontece no submit (ver
  // handleSubmit), com fallback pro mínimo de cada campo se ficar
  // vazio/inválido.
  // Duas etapas: 1) horários e eventos especiais, 2) ordem das
  // apresentações.
  const [step, setStep] = useState<1 | 2>(1);
  const [specialEvents, setSpecialEvents] = useState<SpecialEvent[]>([]);
  const [warmupMinutesInput, setWarmupMinutesInput] = useState("10");
  const [gapMinutesInput, setGapMinutesInput] = useState(
    String(initialGapMinutes),
  );
  // Ordem das apresentações: configuração por EVENTO (vale pra todos
  // os dias), salva junto com cada geração. `categories` null = ainda
  // carregando (ou falhou — aí a geração segue com o que já estava
  // salvo, sem sobrescrever).
  const [orderPrimary, setOrderPrimary] =
    useState<AutoGenerateOrderPrimary>("format");
  const [levelDirection, setLevelDirection] =
    useState<AutoGenerateLevelDirection>("asc");
  const [categoryOrder, setCategoryOrder] = useState<string[] | null>(null);
  const [categories, setCategories] = useState<Category[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    setStep(1);
    setCategories(null);
    setCategoryOrder(null);
    Promise.all([
      scheduleApi.getAutoGenerateSettings(eventId),
      categoriesApi.list(eventId),
    ])
      .then(([settings, loaded]) => {
        if (cancelled) return;
        setOrderPrimary(settings.orderPrimary);
        setLevelDirection(settings.levelDirection);
        setSpecialEvents(settings.specialEvents);
        setCategories(loaded);
        setCategoryOrder(mergeSavedFormatOrder(settings.formatOrder, loaded));
      })
      .catch(() => {
        if (!cancelled)
          setError(
            "Não foi possível carregar as configurações do evento. Feche e tente de novo.",
          );
      });
    return () => {
      cancelled = true;
    };
  }, [open, eventId]);

  function handleResetOrder() {
    setOrderPrimary("format");
    setLevelDirection("asc");
    setCategoryOrder(eventFormatKeysInDefaultOrder(categories ?? []));
  }

  function handleOpenChange(next: boolean) {
    if (next) setGapMinutesInput(String(initialGapMinutes));
    else setError(null);
    onOpenChange(next);
  }

  function handleNext() {
    const problem = findSpecialEventsFormProblem(specialEvents);
    if (problem) {
      setError(problem);
      return;
    }
    setError(null);
    setStep(2);
  }

  async function handleSubmit() {
    setError(null);
    setLoading(true);
    try {
      const warmupMinutes = Math.max(1, Number(warmupMinutesInput) || 0);
      const gapMinutes = Math.max(0, Number(gapMinutesInput) || 0);
      if (categoryOrder === null) return;
      await scheduleApi.updateAutoGenerateSettings(eventId, {
        orderPrimary,
        levelDirection,
        formatOrder: categoryOrder,
        specialEvents,
      });
      await onGenerate(
        {
          startMinutes: parseTimeToMinutes(startTime),
          warmupMinutes,
        },
        gapMinutes,
      );
      handleOpenChange(false);
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.message
          : "Erro inesperado. Tente novamente.",
      );
    } finally {
      setLoading(false);
    }
  }

  const loaded = categoryOrder !== null;

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-h-[92vh] gap-5 overflow-y-auto p-5 sm:max-w-2xl sm:gap-6 sm:p-8">
        <div className="grid min-w-0 gap-1.5">
          <DialogTitle className="text-xl font-medium">
            Gerar cronograma automaticamente
          </DialogTitle>
          <DialogDescription>
            Preenche o dia inteiro a partir das apresentações ainda não
            agendadas, distribuindo entre as pistas. Etapa {step} de 2:{" "}
            {step === 1
              ? "horários e eventos especiais"
              : "ordem das apresentações"}
            .
          </DialogDescription>
        </div>

        {step === 1 ? (
          <div className="grid gap-6">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div className="grid min-w-0 gap-1.5">
                <Label>Horário inicial</Label>
                <input
                  type="time"
                  value={startTime}
                  onChange={(e) => setStartTime(e.target.value)}
                  className="w-full min-w-0 rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
                />
              </div>
              <div className="grid min-w-0 gap-1.5">
                <Label>Duração do aquecimento (min)</Label>
                <input
                  type="number"
                  min={1}
                  value={warmupMinutesInput}
                  onChange={(e) => setWarmupMinutesInput(e.target.value)}
                  className="w-full min-w-0 rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
                />
              </div>
              <div className="grid min-w-0 gap-1.5">
                <Label>Intervalo entre apresentações (min)</Label>
                <input
                  type="number"
                  min={0}
                  value={gapMinutesInput}
                  onChange={(e) => setGapMinutesInput(e.target.value)}
                  className="w-full min-w-0 rounded-md border border-border/60 bg-background px-3 py-2 text-sm text-foreground"
                />
              </div>
            </div>

            <SpecialEventsEditor
              value={specialEvents}
              onChange={setSpecialEvents}
            />
          </div>
        ) : (
          <AutoGenerateOrderFields
            primary={orderPrimary}
            onPrimaryChange={setOrderPrimary}
            levelDirection={levelDirection}
            onLevelDirectionChange={setLevelDirection}
            categoryOrder={categoryOrder}
            onCategoryOrderChange={setCategoryOrder}
            onReset={handleResetOrder}
          />
        )}

        <FormError message={error} />

        <div className="flex justify-between gap-3">
          {step === 1 ? (
            <Button
              variant="outline"
              onClick={() => handleOpenChange(false)}
              disabled={loading}
            >
              Cancelar
            </Button>
          ) : (
            <Button
              variant="outline"
              onClick={() => setStep(1)}
              disabled={loading}
            >
              Voltar
            </Button>
          )}
          {step === 1 ? (
            <Button onClick={handleNext} disabled={!loaded}>
              Próximo
            </Button>
          ) : (
            <Button onClick={handleSubmit} disabled={loading || !loaded}>
              {loading ? "Gerando..." : "Gerar cronograma"}
            </Button>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
