import { useEffect, useState } from "react";
import { Plus, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ResourceColorPicker } from "@/components/ResourceColorPicker";
import { PASTEL_BAND_COLORS } from "@/lib/avatarColor";
import { validateScoreBands } from "@/lib/scoreBands";
import type { ScoreBand } from "@/api/client";

interface ScoreBandsEditorProps {
  bands: ScoreBand[];
  maxScore: number;
  onChange: (bands: ScoreBand[]) => void;
  disabled?: boolean;
}

// Draft de texto separado do `number` de verdade (`min`/`max`) — bug
// real 2026-08-05 (mesmo documentado em AutoGenerateDialog): um input
// number controlado direto pelo valor numérico não deixa o campo ficar
// vazio pra digitar de novo (apagar manda "", `Number("")` vira `0`, o
// input reexibe "0" na hora). Só propaga pro `band.min`/`max` de
// verdade (via `onUpdate`, que sobe até `bandsDraft` em
// EditCriterionPanel) quando o texto já é um número válido — enquanto
// vazio/inválido, o valor anterior fica intacto (não quebra
// `validateScoreBands` nem seria salvo com 0 por engano). Extraído num
// componente próprio (em vez de um hook local dentro do `.map` de
// ScoreBandsEditor) porque `min`/`max` precisam de um `useState`+
// `useEffect` cada, e hooks não podem ser chamados dentro de um loop.
// Os dois `useEffect` abaixo reidratam o draft a partir do prop só
// quando ele muda por um motivo QUE NÃO é a própria digitação (ex:
// `removeBand` desloca os índices e este card passa a representar
// outra faixa) — comparar o número parseado do draft contra o prop
// evita apagar o campo vazio que o usuário está no meio de editar.
function ScoreBandCard({
  band,
  disabled,
  onUpdate,
  onRemove,
}: {
  band: ScoreBand;
  disabled?: boolean;
  onUpdate: (patch: Partial<ScoreBand>) => void;
  onRemove: () => void;
}) {
  const [minDraft, setMinDraft] = useState(() => String(band.min));
  const [maxDraft, setMaxDraft] = useState(() => String(band.max));

  useEffect(() => {
    const parsed = Number(minDraft);
    if (minDraft.trim() !== "" && !Number.isNaN(parsed) && parsed !== band.min) {
      setMinDraft(String(band.min));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [band.min]);

  useEffect(() => {
    const parsed = Number(maxDraft);
    if (maxDraft.trim() !== "" && !Number.isNaN(parsed) && parsed !== band.max) {
      setMaxDraft(String(band.max));
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [band.max]);

  return (
    <div className="flex w-60 shrink-0 flex-col gap-2.5 rounded-lg border border-border/60 bg-muted/30 p-3">
      <div className="flex items-center gap-2">
        <Input
          value={band.name}
          disabled={disabled}
          placeholder="Nome da faixa (ex: Excelente)"
          onChange={(e) => onUpdate({ name: e.target.value })}
          className="flex-1"
        />
        {!disabled && (
          <button
            type="button"
            onClick={onRemove}
            aria-label="Remover faixa"
            className="flex size-8 shrink-0 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-destructive/10 hover:text-destructive"
          >
            <X className="size-4" />
          </button>
        )}
      </div>
      <div className="flex items-center gap-2">
        <Input
          type="number"
          step={0.01}
          value={minDraft}
          disabled={disabled}
          onChange={(e) => {
            setMinDraft(e.target.value);
            const parsed = Number(e.target.value);
            if (e.target.value.trim() !== "" && !Number.isNaN(parsed)) onUpdate({ min: parsed });
          }}
          className="w-20"
        />
        <span className="text-sm text-muted-foreground">até</span>
        <Input
          type="number"
          step={0.01}
          value={maxDraft}
          disabled={disabled}
          onChange={(e) => {
            setMaxDraft(e.target.value);
            const parsed = Number(e.target.value);
            if (e.target.value.trim() !== "" && !Number.isNaN(parsed)) onUpdate({ max: parsed });
          }}
          className="w-20"
        />
      </div>
      <textarea
        value={band.description ?? ""}
        disabled={disabled}
        placeholder="Descrição da faixa (opcional)"
        rows={4}
        onChange={(e) => onUpdate({ description: e.target.value || null })}
        className="w-full rounded-lg border border-transparent bg-background px-3 py-2 text-sm text-foreground transition-colors outline-none placeholder:text-muted-foreground hover:bg-muted/70 focus-visible:border-primary focus-visible:bg-primary/[0.06] disabled:cursor-not-allowed disabled:opacity-60"
      />
      <ResourceColorPicker
        value={band.color}
        onChange={(color) => !disabled && onUpdate({ color })}
        colors={PASTEL_BAND_COLORS}
      />
    </div>
  );
}

export function ScoreBandsEditor({ bands, maxScore, onChange, disabled }: ScoreBandsEditorProps) {
  const error = validateScoreBands(bands, maxScore);

  function updateBand(index: number, patch: Partial<ScoreBand>) {
    onChange(bands.map((band, i) => (i === index ? { ...band, ...patch } : band)));
  }

  function removeBand(index: number) {
    onChange(bands.filter((_, i) => i !== index));
  }

  function addBand() {
    const previousMax = bands.length > 0 ? bands[bands.length - 1].max : 0;
    onChange([
      ...bands,
      {
        name: "",
        description: null,
        color: PASTEL_BAND_COLORS[bands.length % PASTEL_BAND_COLORS.length],
        min: previousMax,
        max: previousMax,
      },
    ]);
  }

  return (
    <div className="grid min-w-0 gap-3">
      {/* Faixas lado a lado com scroll horizontal próprio (não empilhadas
          verticalmente). `min-w-0` em cada nível da cadeia é necessário
          porque nem grid nem flex limitam a largura de um item pelo
          conteúdo por padrão — sem isso, a lista vaza visualmente e quem
          acaba rolando é a página inteira (`<main>`), não só esta lista. */}
      <div className="flex min-w-0 gap-3 overflow-x-auto pb-1">
        {bands.map((band, index) => (
          <ScoreBandCard
            key={index}
            band={band}
            disabled={disabled}
            onUpdate={(patch) => updateBand(index, patch)}
            onRemove={() => removeBand(index)}
          />
        ))}
      </div>

      {!disabled && (
        <Button type="button" variant="outline" size="sm" onClick={addBand}>
          <Plus data-icon="inline-start" />
          Adicionar faixa
        </Button>
      )}

      {error && <p className="text-xs text-amber-600">{error}</p>}
    </div>
  );
}
