import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Trash2 } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FormError } from "@/components/FormError";
import { computeResourceTimes, formatMinutes } from "@/lib/scheduleTime";
import { ApiError, scheduleApi, type ScheduleDay } from "@/api/client";

interface SpecialEventDetailsDialogProps {
  eventId: string;
  day: ScheduleDay;
  entryId: string | null;
  onOpenChange: (open: boolean) => void;
  onChanged: () => void;
}

// Aberto ao clicar num evento especial (Almoço, Abertura, Premiação,
// intervalo personalizado etc.) já lançado na linha do tempo/tabela —
// irmão do PresentationDetailsDialog, mas sem a seção "Mover" (o
// arraste na própria timeline já cobre reposicionar; início/fim são
// sempre derivados de ordem+duração, nunca um valor próprio a editar).
// Pedido do usuário (2026-09-22): antes só dava pra editar removendo e
// recriando pela biblioteca de componentes.
export function SpecialEventDetailsDialog({
  eventId,
  day,
  entryId,
  onOpenChange,
  onChanged,
}: SpecialEventDetailsDialogProps) {
  const [label, setLabel] = useState("");
  // STRING, não number — mesmo motivo já documentado em
  // CustomIntervalDialog/AutoGenerateDialog: com state number direto,
  // apagar o campo pra digitar outro valor reexibe "0" antes do
  // usuário conseguir digitar.
  const [durationMinutesInput, setDurationMinutesInput] = useState("15");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const times = useMemo(
    () => computeResourceTimes(day.resources, day.startMinutes),
    [day],
  );

  const entry = useMemo(() => {
    if (!entryId) return null;
    for (const resource of day.resources) {
      const found = resource.entries.find((e) => e.id === entryId);
      if (found) return found;
    }
    return null;
  }, [day, entryId]);

  const resource = useMemo(() => {
    if (!entryId) return null;
    return day.resources.find((r) => r.entries.some((e) => e.id === entryId)) ?? null;
  }, [day, entryId]);

  useEffect(() => {
    setLabel(entry?.label ?? "");
    setDurationMinutesInput(String(entry?.durationMinutes ?? 15));
    setError(null);
  }, [entryId, entry?.label, entry?.durationMinutes]);

  if (!entry || !resource) return null;

  const t = times.get(entry.id);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!label.trim()) {
      setError("Informe um nome.");
      return;
    }
    const durationMinutes = Number(durationMinutesInput);
    if (!durationMinutes || durationMinutes < 1) {
      setError("Informe uma duração válida.");
      return;
    }
    setError(null);
    setLoading(true);
    try {
      await scheduleApi.updateEntry(eventId, day.id, entry!.id, {
        label: label.trim(),
        durationMinutes,
      });
      onChanged();
      onOpenChange(false);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Não foi possível salvar.");
    } finally {
      setLoading(false);
    }
  }

  async function handleRemove() {
    setError(null);
    setLoading(true);
    try {
      await scheduleApi.removeEntry(eventId, day.id, entry!.id);
      onChanged();
      onOpenChange(false);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Não foi possível remover este evento.");
      setLoading(false);
    }
  }

  return (
    <Dialog open={entryId !== null} onOpenChange={onOpenChange}>
      <DialogContent className="gap-6 p-8 sm:max-w-md">
        <div className="grid gap-1.5">
          <DialogTitle className="text-xl font-medium">Editar evento</DialogTitle>
          <DialogDescription>{resource.name}</DialogDescription>
        </div>

        <form onSubmit={handleSubmit} className="grid gap-5">
          <div className="grid gap-2 rounded-lg border border-border/60 p-4 text-sm">
            <div className="flex items-center justify-between gap-3">
              <span className="text-muted-foreground">Horário</span>
              <span className="font-medium text-foreground">
                {t ? `${formatMinutes(t.startMinutes)} – ${formatMinutes(t.endMinutes)}` : "—"}
              </span>
            </div>
            <p className="text-xs text-muted-foreground">
              Para mudar o horário de início, arraste este evento na linha do tempo.
            </p>
          </div>

          <div className="grid gap-2">
            <Label htmlFor="special-event-name">Nome</Label>
            <Input
              id="special-event-name"
              autoFocus
              value={label}
              onChange={(e) => setLabel(e.target.value)}
              required
            />
          </div>

          <div className="grid gap-2">
            <Label htmlFor="special-event-duration">Duração (min)</Label>
            <Input
              id="special-event-duration"
              type="number"
              min={1}
              value={durationMinutesInput}
              onChange={(e) => setDurationMinutesInput(e.target.value)}
              required
            />
          </div>

          <FormError message={error} />

          <Button type="submit" disabled={loading} className="w-full">
            {loading ? "Salvando..." : "Salvar"}
          </Button>
        </form>

        <Button
          onClick={handleRemove}
          disabled={loading}
          variant="ghost"
          className="w-full text-destructive hover:bg-destructive/10 hover:text-destructive"
        >
          <Trash2 data-icon="inline-start" />
          Remover evento
        </Button>
      </DialogContent>
    </Dialog>
  );
}
