import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { format, parseISO } from "date-fns";
import { cn } from "@/lib/utils";
import {
  ArrowLeft,
  ArrowRight,
  CalendarClock,
  Copy,
  GanttChartSquare,
  Loader2,
  Sparkles,
  Star,
  Table2,
} from "lucide-react";
import {
  DndContext,
  DragOverlay,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
  type DragMoveEvent,
  type DragStartEvent,
} from "@dnd-kit/core";
import { AppSidebar } from "@/components/AppSidebar";
import { NotificationBell } from "@/components/NotificationBell";
import { useNotificationsUnreadCount } from "@/lib/useNotificationsUnreadCount";
import { Button } from "@/components/ui/button";
import { ScheduleDaySettingsBar } from "@/components/ScheduleDaySettingsBar";
import {
  ScheduleTimeline,
  SCHEDULE_PX_PER_MINUTE,
  RESOURCE_DRAG_PREFIX,
  RESOURCE_DROP_PREFIX,
  ResourceHandleCard,
} from "@/components/ScheduleTimeline";
import { ScheduleTableView, TABLE_CELL_PREFIX } from "@/components/ScheduleTableView";
import { UnscheduledTeamsPanel, UnscheduledItemCard } from "@/components/UnscheduledTeamsPanel";
import {
  EventComponentsLibrary,
  ComponentBlockCard,
  type ComponentBlockDef,
} from "@/components/EventComponentsLibrary";
import { AutoGenerateDialog } from "@/components/AutoGenerateDialog";
import { EditResourceDialog } from "@/components/EditResourceDialog";
import { CreateResourceDialog } from "@/components/CreateResourceDialog";
import { ScheduleSummaryFooter } from "@/components/ScheduleSummaryFooter";
import { PresentationDetailsDialog } from "@/components/PresentationDetailsDialog";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import { ScheduleOverflowDialog } from "@/components/ScheduleOverflowDialog";
import { findScheduleConflicts } from "@/lib/scheduleConflicts";
import { computeResourceTimes } from "@/lib/scheduleTime";
import { SCHEDULE_TYPE_STYLES } from "@/lib/scheduleEntryDisplay";
import { useEventSetupGuard } from "@/lib/useEventSetupGuard";
import {
  scheduleApi,
  usersApi,
  ApiError,
  type AutoGenerateSchedulePayload,
  type ScheduleDay,
  type ScheduleEntry,
  type ScheduleResource,
  type UnscheduledPair,
  type UpdateScheduleDayPayload,
  type UserProfile,
} from "@/api/client";
import { useAuthStore } from "@/store/auth";

// Espelha os payloads passados via `data` em cada useDraggable (ver
// UnscheduledTeamsPanel/EventComponentsLibrary/ScheduleEntryCard/
// ScheduleTimeline) — usado só pra desenhar a prévia certa no
// DragOverlay abaixo, não pra lógica de negócio (essa continua toda em
// handleDragEnd, a partir do id).
type ActiveDragData =
  | { kind: "unscheduled"; pair: UnscheduledPair }
  | { kind: "component"; def: ComponentBlockDef }
  | { kind: "entry"; entry: ScheduleEntry; title: string; subtitle: string | null; timeRange: string }
  | { kind: "resource"; resource: ScheduleResource };

export function SchedulePage() {
  const { id } = useParams<{ id: string }>();
  const notificationsUnreadCount = useNotificationsUnreadCount(id);
  useEventSetupGuard(id);
  const navigate = useNavigate();
  const logout = useAuthStore((s) => s.logout);

  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [days, setDays] = useState<ScheduleDay[]>([]);
  const [selectedDayId, setSelectedDayId] = useState<string | null>(null);
  const [unscheduled, setUnscheduled] = useState<UnscheduledPair[]>([]);
  const [addingDay, setAddingDay] = useState(false);
  const [autoGenerateOpen, setAutoGenerateOpen] = useState(false);
  const [editingResourceId, setEditingResourceId] = useState<string | null>(null);
  const [detailsEntryId, setDetailsEntryId] = useState<string | null>(null);
  const [createResourceOpen, setCreateResourceOpen] = useState(false);
  const [replicateOpen, setReplicateOpen] = useState(false);
  const [dayToDelete, setDayToDelete] = useState<ScheduleDay | null>(null);
  const [overflow, setOverflow] = useState<{
    dayId: string;
    newEndMinutes: number;
    undo: () => Promise<void>;
  } | null>(null);
  const [viewMode, setViewMode] = useState<"timeline" | "table">("timeline");
  const [error, setError] = useState<string | null>(null);
  const [activeDragEntryId, setActiveDragEntryId] = useState<string | null>(null);
  const [activeDragDelta, setActiveDragDelta] = useState({ x: 0, y: 0 });
  // Só pra desenhar a prévia certa no DragOverlay (ver return abaixo) —
  // nenhuma lógica de negócio depende disto, `handleDragEnd` continua
  // resolvendo tudo a partir do id.
  const [activeDragData, setActiveDragData] = useState<ActiveDragData | null>(null);
  // Cobre tanto soltar um drag (card já desaparece do lugar de origem
  // na hora, dnd-kit reseta o estado de drag imediatamente) quanto
  // remover uma apresentação (botão "X"/"Remover apresentação") — nos
  // dois casos a reconciliação de verdade no backend (aquecimento/
  // intervalos/pistas, ver ScheduleService) pode levar um tempo
  // perceptível, e sem nenhum feedback nesse meio tempo parecia que a
  // ação tinha falhado silenciosamente (pedido do usuário, 2026-08-05).
  // Fica true do início ao fim da chamada de rede (ver handleDragEnd/
  // handleRemoveEntry), não é otimista: o dado real só chega quando
  // `refetchDays` resolve.
  const [scheduleMutationPending, setScheduleMutationPending] = useState(false);

  useEffect(() => {
    usersApi.me().then(setProfile).catch(() => setProfile(null));
  }, []);

  useEffect(() => {
    if (!id) return;
    refetchDays();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  // Equipes não agendadas é por dia (cada equipe/categoria pode se
  // apresentar uma vez em cada dia — ver ScheduleService), então
  // refaz o fetch sempre que o dia selecionado mudar, não só ao
  // montar a página.
  useEffect(() => {
    if (!id || !selectedDayId) return;
    refetchUnscheduled();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id, selectedDayId]);

  function refetchDays() {
    if (!id) return;
    scheduleApi
      .listDays(id)
      .then((loaded) => {
        setDays(loaded);
        setSelectedDayId((current) => current ?? loaded[0]?.id ?? null);
      })
      .catch(() => setError("Não foi possível carregar o cronograma. Tente novamente."));
  }

  function refetchUnscheduled() {
    if (!id || !selectedDayId) return;
    scheduleApi
      .getUnscheduled(id, selectedDayId)
      .then(setUnscheduled)
      .catch(() => setUnscheduled([]));
  }

  const selectedDay = days.find((d) => d.id === selectedDayId) ?? null;
  const conflicts = useMemo(
    () => (selectedDay ? findScheduleConflicts(selectedDay) : new Map<string, string[]>()),
    [selectedDay],
  );

  // Enquanto o usuário arrasta uma apresentação, o aquecimento
  // vinculado a ela (linkedEntryId) "anda junto" visualmente — só
  // efeito visual (ScheduleEntryCard/TableEntryCell espelham este
  // deslocamento no aquecimento), o reposicionamento de verdade
  // acontece no backend ao soltar (ver ScheduleService.moveEntry, que
  // agora recalcula o aquecimento junto quando a apresentação move).
  const peerDrag = useMemo(() => {
    if (!activeDragEntryId || !selectedDay) return null;
    const allEntries = selectedDay.resources.flatMap((r) => r.entries);
    const activeEntry = allEntries.find((e) => e.id === activeDragEntryId);
    if (!activeEntry || activeEntry.type !== "presentation") return null;
    // O intervalo "Aguardando aquecimento" também tem linkedEntryId
    // apontando pra esta apresentação (ver ScheduleService) — sem
    // filtrar por type, o find abaixo podia pegar esse intervalo em
    // vez do aquecimento de verdade.
    const warmup = allEntries.find(
      (e) => e.type === "warmup" && e.linkedEntryId === activeEntry.id,
    );
    if (!warmup) return null;
    return { entryId: warmup.id, x: activeDragDelta.x, y: activeDragDelta.y };
  }, [activeDragEntryId, activeDragDelta, selectedDay]);

  function handleDragStart(event: DragStartEvent) {
    setActiveDragEntryId(String(event.active.id));
    setActiveDragDelta({ x: 0, y: 0 });
    setActiveDragData((event.active.data.current as ActiveDragData | undefined) ?? null);
  }

  function handleDragMove(event: DragMoveEvent) {
    setActiveDragDelta({ x: event.delta.x, y: event.delta.y });
  }

  function clearActiveDrag() {
    setActiveDragEntryId(null);
    setActiveDragDelta({ x: 0, y: 0 });
    setActiveDragData(null);
  }

  function handleLogout() {
    logout();
    navigate("/login");
  }

  async function handleAddDay() {
    if (!id) return;
    setAddingDay(true);
    try {
      const day = await scheduleApi.addDay(id);
      setDays((prev) => [...prev, day]);
      setSelectedDayId(day.id);
    } catch {
      setError("Não foi possível adicionar um novo dia.");
    } finally {
      setAddingDay(false);
    }
  }

  async function handleConfirmDeleteDay() {
    if (!id || !dayToDelete) return;
    await scheduleApi.removeDay(id, dayToDelete.id);
    // Se o dia excluído era o selecionado, limpa pra refetchDays cair
    // no primeiro dia restante (ver `current ?? loaded[0]?.id` ali).
    if (selectedDayId === dayToDelete.id) {
      setSelectedDayId(null);
    }
    refetchDays();
  }

  function handleUpdateDay(payload: UpdateScheduleDayPayload) {
    if (!id || !selectedDayId) return;
    scheduleApi
      .updateDay(id, selectedDayId, payload)
      .then((updated) => {
        setDays((prev) => prev.map((d) => (d.id === updated.id ? updated : d)));
      })
      .catch(() => setError("Não foi possível atualizar as configurações do dia."));
  }

  // Chamado depois de criar um item novo (apresentação, componente ou
  // intervalo personalizado) — o horário final de verdade só se sabe
  // depois que o backend já reconciliou aquecimentos/esperas (ver
  // ScheduleService.reconcileWarmupDelays/reconcileMatGaps), então o
  // recarregamento aqui já é o dado definitivo, não uma previsão.
  // Se algum recurso do dia passou do "Horário do dia" configurado,
  // guarda a ação de desfazer (`undo`) e abre o popup — o item já foi
  // criado no backend nesse ponto, só decide se ele fica (estendendo o
  // fim do dia) ou é removido de novo.
  async function checkDayOverflowAndMaybePrompt(dayId: string, undo: () => Promise<void>) {
    if (!id) return;
    const loaded = await scheduleApi.listDays(id);
    setDays(loaded);
    const day = loaded.find((d) => d.id === dayId);
    if (!day) return;
    const times = computeResourceTimes(day.resources, day.startMinutes);
    let maxEndMinutes = day.startMinutes;
    for (const t of times.values()) maxEndMinutes = Math.max(maxEndMinutes, t.endMinutes);
    if (maxEndMinutes > day.endMinutes) {
      setOverflow({ dayId, newEndMinutes: maxEndMinutes, undo });
    }
  }

  async function handleExtendDayEnd() {
    if (!id || !overflow) return;
    const updated = await scheduleApi.updateDay(id, overflow.dayId, {
      endMinutes: overflow.newEndMinutes,
    });
    setDays((prev) => prev.map((d) => (d.id === updated.id ? updated : d)));
    setOverflow(null);
  }

  async function handleCancelOverflow() {
    if (!overflow) return;
    await overflow.undo();
    setOverflow(null);
  }

  function handleRemoveEntry(entryId: string) {
    if (!id || !selectedDayId) return;
    setScheduleMutationPending(true);
    scheduleApi
      .removeEntry(id, selectedDayId, entryId)
      .then(() => {
        refetchDays();
        refetchUnscheduled();
      })
      .catch(() => setError("Não foi possível remover este item do cronograma."))
      .finally(() => setScheduleMutationPending(false));
  }

  async function handleAutoGenerate(payload: AutoGenerateSchedulePayload, gapMinutes: number) {
    if (!id || !selectedDayId) return;
    // `autoGenerate` no backend lê o intervalo padrão do PRÓPRIO dia
    // (ScheduleDay.defaultGapMinutes, mesmo campo da barra de
    // configurações) em vez de receber um valor solto no payload —
    // por isso salva aqui ANTES de gerar (awaited), garantindo que o
    // valor escolhido no popup seja o mesmo usado na geração.
    if (gapMinutes !== selectedDay?.defaultGapMinutes) {
      await scheduleApi.updateDay(id, selectedDayId, { defaultGapMinutes: gapMinutes });
    }
    const updated = await scheduleApi.autoGenerate(id, selectedDayId, payload);
    setDays((prev) => prev.map((d) => (d.id === updated.id ? updated : d)));
    refetchUnscheduled();
  }

  function handleCustomIntervalCreated(created: ScheduleEntry[]) {
    if (!id || !selectedDay) return;
    const dayId = selectedDay.id;
    const entry = created[0];
    checkDayOverflowAndMaybePrompt(dayId, async () => {
      if (entry) await scheduleApi.removeEntry(id, dayId, entry.id);
      refetchDays();
    });
  }

  async function handleReplicateToAllDays() {
    if (!id || !selectedDayId) return;
    const updated = await scheduleApi.replicateToAllDays(id, selectedDayId);
    setDays(updated);
    refetchUnscheduled();
  }

  function handleDragEnd(event: DragEndEvent) {
    clearActiveDrag();
    if (!id || !selectedDay) return;
    const { active, over } = event;
    if (!over) return;

    const activeIdRaw = String(active.id);
    const overIdRaw = String(over.id);

    // Reordenar as próprias linhas de recurso — arrastar o "handle"
    // (coluna esquerda) de um recurso sobre o de outro insere o
    // arrastado na posição do alvo (empurra os demais).
    if (activeIdRaw.startsWith(RESOURCE_DRAG_PREFIX)) {
      if (!overIdRaw.startsWith(RESOURCE_DROP_PREFIX)) return;
      const sourceResourceId = activeIdRaw.slice(RESOURCE_DRAG_PREFIX.length);
      const targetResourceId = overIdRaw.slice(RESOURCE_DROP_PREFIX.length);
      if (sourceResourceId === targetResourceId) return;

      const sortedResources = [...selectedDay.resources].sort((a, b) => a.order - b.order);
      const targetIndex = sortedResources.findIndex((r) => r.id === targetResourceId);
      if (targetIndex === -1) return;

      setScheduleMutationPending(true);
      scheduleApi
        .moveResource(id, selectedDay.id, sourceResourceId, { order: targetIndex })
        .then(refetchDays)
        .catch(() => setError("Não foi possível reordenar este recurso."))
        .finally(() => setScheduleMutationPending(false));
      return;
    }

    // A visão em tabela já solta direto num horário (o id do
    // droppable é "table-cell:<resourceId>:<rowStart>", ver
    // ScheduleTableView) — não precisa de conta de pixel nenhuma, só a
    // timeline calcula a posição a partir do deslocamento horizontal
    // do arrasto.
    let resourceId: string;
    let dropMinutes: number;
    if (overIdRaw.startsWith(TABLE_CELL_PREFIX)) {
      const rest = overIdRaw.slice(TABLE_CELL_PREFIX.length);
      const sepIndex = rest.lastIndexOf(":");
      resourceId = rest.slice(0, sepIndex);
      dropMinutes = Number(rest.slice(sepIndex + 1));
    } else {
      resourceId = overIdRaw;
      const overRect = over.rect;
      const activeRect = active.rect.current.translated;
      const dropX = activeRect ? activeRect.left - overRect.left : 0;
      dropMinutes = selectedDay.startMinutes + dropX / SCHEDULE_PX_PER_MINUTE;
    }

    const resource = selectedDay.resources.find((r) => r.id === resourceId);
    if (!resource) return;

    const times = computeResourceTimes(selectedDay.resources, selectedDay.startMinutes);
    const sortedEntries = [...resource.entries].sort((a, b) => a.order - b.order);
    let insertIndex = sortedEntries.length;
    for (let i = 0; i < sortedEntries.length; i++) {
      const t = times.get(sortedEntries[i].id);
      if (t && dropMinutes < (t.startMinutes + t.endMinutes) / 2) {
        insertIndex = i;
        break;
      }
    }

    if (activeIdRaw.startsWith("unscheduled:")) {
      const [, teamId, categoryId] = activeIdRaw.split(":");
      const dayId = selectedDay.id;
      setScheduleMutationPending(true);
      scheduleApi
        .createEntry(id, dayId, {
          resourceId,
          type: "presentation",
          order: insertIndex,
          teamId,
          categoryId,
        })
        .then((created) => {
          refetchUnscheduled();
          const presentation = created.find((e) => e.type === "presentation");
          return checkDayOverflowAndMaybePrompt(dayId, async () => {
            if (presentation) await scheduleApi.removeEntry(id, dayId, presentation.id);
            refetchDays();
            refetchUnscheduled();
          });
        })
        .catch((err) =>
          setError(
            err instanceof ApiError ? err.message : "Não foi possível agendar esta apresentação.",
          ),
        )
        .finally(() => setScheduleMutationPending(false));
      return;
    }

    if (activeIdRaw.startsWith("component:")) {
      const [, type, durationStr, label] = activeIdRaw.split(":");
      const dayId = selectedDay.id;
      setScheduleMutationPending(true);
      scheduleApi
        .createEntry(id, dayId, {
          resourceId,
          type: type as "break" | "ceremony" | "award",
          order: insertIndex,
          durationMinutes: Number(durationStr),
          label: label || undefined,
        })
        .then((created) => {
          const entry = created[0];
          return checkDayOverflowAndMaybePrompt(dayId, async () => {
            if (entry) await scheduleApi.removeEntry(id, dayId, entry.id);
            refetchDays();
          });
        })
        .catch(() => setError("Não foi possível adicionar este componente."))
        .finally(() => setScheduleMutationPending(false));
      return;
    }

    setScheduleMutationPending(true);
    scheduleApi
      .moveEntry(id, selectedDay.id, activeIdRaw, { resourceId, order: insertIndex })
      .then(refetchDays)
      .catch(() => setError("Não foi possível mover este item."))
      .finally(() => setScheduleMutationPending(false));
  }

  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }));

  return (
    <div className="flex h-svh bg-background">
      <AppSidebar profile={profile} onLogout={handleLogout} />

      <DndContext
        sensors={sensors}
        onDragStart={handleDragStart}
        onDragMove={handleDragMove}
        onDragEnd={handleDragEnd}
        onDragCancel={clearActiveDrag}
      >
        <main className="flex flex-1 flex-col overflow-y-auto">
          <div className="flex items-center justify-between px-10 pt-6">
            <button
              type="button"
              onClick={() => navigate(`/events/${id}/setup`)}
              className="flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              <ArrowLeft className="size-4" />
              Voltar para configuração do evento
            </button>
            <NotificationBell unreadCount={notificationsUnreadCount} />
          </div>

          <div className="flex min-h-0 flex-1 flex-col gap-6 px-10 pb-10">
            <div className="mt-6 flex flex-wrap items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground">
                  <CalendarClock className="size-5" />
                </div>
                <div>
                  <h1 className="text-2xl font-semibold text-foreground">Cronograma do Evento</h1>
                  <p className="mt-1 text-sm text-muted-foreground">
                    Planeje a utilização dos recursos do dia (pistas, aquecimentos e outros).
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                {days.length > 1 && (
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setReplicateOpen(true)}
                    disabled={!selectedDay}
                  >
                    <Copy className="size-4" />
                    Repetir em todos os dias
                  </Button>
                )}
                <Button type="button" onClick={() => setAutoGenerateOpen(true)} disabled={!selectedDay}>
                  <Sparkles className="size-4" />
                  Gerar automaticamente
                </Button>
              </div>
            </div>

            {selectedDay && (
              <>
                <ScheduleDaySettingsBar
                  days={days}
                  day={selectedDay}
                  onSelectDay={setSelectedDayId}
                  onAddDay={handleAddDay}
                  addingDay={addingDay}
                  onUpdate={handleUpdateDay}
                  onDeleteDay={(dayId) =>
                    setDayToDelete(days.find((d) => d.id === dayId) ?? null)
                  }
                />

                <div className="grid flex-1 grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
                  {/* Abaixo de `xl` (cobre qualquer tablet, mesmo em
                      paisagem — a grade vira 1 coluna só) o grid não tem
                      mais uma linha "esticável" pra essa coluna se
                      encaixar (linhas de grid em `grid-cols-1` usam
                      altura de conteúdo, não preenchem o espaço
                      disponível) — sem um `min-h` explícito aqui, a
                      timeline (que depende de `flex-1` encadeado até
                      esta div) colapsava praticamente pra 0 de altura,
                      ficando invisível. `min-h-[70vh]` garante espaço de
                      verdade pra ela mesmo sem o esticamento do grid;
                      resultado é a página inteira (não só esta coluna)
                      precisar rolar pra ver o painel ao lado — trade-off
                      pedido pelo usuário (prefere conteúdo grande com
                      scroll a tudo espremido pra caber sem rolar).

                      O grid (div acima) NÃO tem `min-h-0` em NENHUM
                      breakpoint, de propósito — bug real 2026-08-05,
                      encontrado de novo em tablet PAISAGEM depois de um
                      primeiro fix que só cobria retrato (largura abaixo
                      de `xl`). `min-h-0` incondicional (ou só `xl:`,
                      como a primeira tentativa) deixa o algoritmo de
                      flexbox encolher o grid abaixo do que o CONTEÚDO
                      dele exige — e em paisagem/desktop (`xl`, 2
                      colunas) esse piso não vem só do `min-h-[70vh]`
                      daqui, vem também do `min-h-72` incondicional da
                      própria ScheduleTimeline (garante 4 recursos
                      visíveis mesmo em telas curtas) — encolher o grid
                      além disso deixa a timeline vazar (`overflow:
                      visible`) pra fora dele e sobrepor o banner "Próxima
                      etapa recomendada" seguinte. SEM `min-h-0` aqui, o
                      grid herda `min-height: auto` (baseado no
                      conteúdo) em qualquer tela — `flex-1` ainda deixa
                      ele CRESCER pra preencher espaço de sobra quando
                      há (visual idêntico ao anterior em telas com
                      espaço confortável), só não deixa mais ENCOLHER
                      além do piso real; sem espaço suficiente, a página
                      cresce/rola (`main` já é `overflow-y-auto`) em vez
                      de sobrepor. */}
                  <div className="flex min-h-[70vh] min-w-0 flex-col gap-6 xl:min-h-0">
                    <div className="flex items-center justify-between gap-3">
                      <div className="flex items-center gap-1 self-start rounded-lg border border-border/60 bg-muted/30 p-1">
                        <Button
                          type="button"
                          size="sm"
                          variant={viewMode === "timeline" ? "default" : "ghost"}
                          onClick={() => setViewMode("timeline")}
                        >
                          <GanttChartSquare className="size-4" />
                          Linha do tempo
                        </Button>
                        <Button
                          type="button"
                          size="sm"
                          variant={viewMode === "table" ? "default" : "ghost"}
                          onClick={() => setViewMode("table")}
                        >
                          <Table2 className="size-4" />
                          Tabela
                        </Button>
                      </div>
                    </div>
                    {viewMode === "timeline" ? (
                      <ScheduleTimeline
                        day={selectedDay}
                        conflicts={conflicts}
                        onRemoveEntry={handleRemoveEntry}
                        onOpenDetails={setDetailsEntryId}
                        onAddResource={() => setCreateResourceOpen(true)}
                        onEditResource={setEditingResourceId}
                        peerDrag={peerDrag}
                      />
                    ) : (
                      <ScheduleTableView
                        day={selectedDay}
                        conflicts={conflicts}
                        onRemoveEntry={handleRemoveEntry}
                        peerDrag={peerDrag}
                      />
                    )}
                    {/* Movido pra aqui (era logo no topo da página,
                        antes até do cabeçalho "Cronograma do Evento") —
                        pedido do usuário 2026-08-05: passava
                        despercebido porque quem está montando o
                        cronograma tem o olho na timeline/tabela, não no
                        topo da página, que já ficou fora da tela numa
                        página comprida. */}
                    {error && <p className="text-sm text-destructive">{error}</p>}
                    <ScheduleSummaryFooter day={selectedDay} />
                  </div>
                  <div className="flex flex-col gap-6 overflow-y-auto">
                    <UnscheduledTeamsPanel
                      pairs={unscheduled}
                      ignoreUnscheduled={selectedDay.ignoreUnscheduledPresentations}
                      onToggleIgnoreUnscheduled={(value) =>
                        handleUpdateDay({ ignoreUnscheduledPresentations: value })
                      }
                    />
                    <EventComponentsLibrary
                      eventId={id!}
                      day={selectedDay}
                      onCreated={handleCustomIntervalCreated}
                    />
                  </div>
                </div>

                <div className="flex flex-col gap-4 rounded-xl border border-amber-300/60 bg-amber-50 p-5 sm:flex-row sm:items-center sm:justify-between dark:border-amber-400/20 dark:bg-amber-500/10">
                  <div className="flex items-start gap-3">
                    <div className="flex size-10 shrink-0 items-center justify-center rounded-full bg-amber-400/20 text-amber-600 dark:text-amber-400">
                      <Star className="size-5" />
                    </div>
                    <div>
                      <p className="font-semibold text-foreground">Próxima etapa recomendada</p>
                      <p className="text-sm text-muted-foreground">
                        Agora monte o painel de jurados, definindo quem julga cada sistema de
                        pontuação.
                      </p>
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => navigate(`/events/${id}/judging`)}
                    className="flex shrink-0 items-center justify-center gap-2 rounded-lg border border-primary/40 px-4 py-2.5 text-sm font-medium text-primary transition-colors hover:bg-primary/10"
                  >
                    Ir para painel de jurados
                    <ArrowRight className="size-4" />
                  </button>
                </div>
              </>
            )}
          </div>
        </main>

        {/* Renderiza num portal (document.body), fora de qualquer
            ancestral com overflow — é exatamente isso que resolve o bug
            de sumir ao arrastar pra fora do painel de equipes/
            componentes ou pra fora da área visível da timeline (bug
            real 2026-08-05: os cards são movidos com `transform` mas
            continuam fisicamente dentro do contêiner de origem, que
            tem scroll próprio; assim que o `transform` empurra o card
            além da borda dele, o `overflow` clipa — some mesmo com o
            dedo/mouse ainda "arrastando"). O conteúdo espelha o
            elemento de origem (ver *Card exportados de cada
            componente), só o suficiente pra dar feedback visual — a
            lógica de mover/criar continua inteira em handleDragEnd. */}
        <DragOverlay>
          {activeDragData?.kind === "unscheduled" && (
            <div className="flex items-center gap-2 rounded-lg border border-border/60 bg-card p-2.5 text-sm shadow-lg">
              <UnscheduledItemCard pair={activeDragData.pair} />
            </div>
          )}
          {activeDragData?.kind === "component" && (
            <div className="flex items-center gap-2 rounded-lg border border-border/60 bg-card p-2.5 text-sm shadow-lg">
              <ComponentBlockCard def={activeDragData.def} />
            </div>
          )}
          {activeDragData?.kind === "resource" && (
            <div className="w-36 rounded-lg border border-border/60 bg-card px-3 py-2 shadow-lg">
              <ResourceHandleCard resource={activeDragData.resource} />
            </div>
          )}
          {activeDragData?.kind === "entry" && (
            <div
              className={cn(
                "flex max-w-56 flex-col justify-center rounded-md border px-2 py-1 text-xs shadow-lg",
                SCHEDULE_TYPE_STYLES[activeDragData.entry.type].bg,
                SCHEDULE_TYPE_STYLES[activeDragData.entry.type].border,
                SCHEDULE_TYPE_STYLES[activeDragData.entry.type].text,
              )}
            >
              <p className="truncate font-medium">{activeDragData.title}</p>
              {activeDragData.subtitle && (
                <p className="truncate opacity-80">{activeDragData.subtitle}</p>
              )}
              <p className="truncate opacity-70">{activeDragData.timeRange}</p>
            </div>
          )}
        </DragOverlay>
      </DndContext>

      <AutoGenerateDialog
        open={autoGenerateOpen}
        onOpenChange={setAutoGenerateOpen}
        initialGapMinutes={selectedDay?.defaultGapMinutes ?? 0}
        onGenerate={handleAutoGenerate}
      />

      {id && selectedDay && (
        <EditResourceDialog
          eventId={id}
          dayId={selectedDay.id}
          resourceId={editingResourceId}
          allResources={selectedDay.resources}
          onOpenChange={(open) => !open && setEditingResourceId(null)}
          onChanged={refetchDays}
        />
      )}

      {id && selectedDay && (
        <PresentationDetailsDialog
          eventId={id}
          day={selectedDay}
          entryId={detailsEntryId}
          conflictReasons={detailsEntryId ? conflicts.get(detailsEntryId) ?? [] : []}
          onOpenChange={(open) => !open && setDetailsEntryId(null)}
          onChanged={() => {
            refetchDays();
            refetchUnscheduled();
          }}
        />
      )}

      {id && selectedDay && (
        <CreateResourceDialog
          eventId={id}
          dayId={selectedDay.id}
          existingResources={selectedDay.resources}
          open={createResourceOpen}
          onOpenChange={setCreateResourceOpen}
          onCreated={refetchDays}
        />
      )}

      <ConfirmDialog
        open={replicateOpen}
        onOpenChange={setReplicateOpen}
        title="Repetir cronograma em todos os dias"
        description="O horário do dia (início/fim, tempo de aquecimento), as pistas, aquecimentos, componentes (Almoço, Abertura, Premiação, Contestação de notas, intervalos personalizados) e as apresentações/aquecimentos das equipes do dia selecionado serão copiados para todos os outros dias do evento — substituindo completamente o que já existir neles."
        confirmLabel="Repetir mesmo assim"
        confirmingLabel="Repetindo..."
        onConfirm={handleReplicateToAllDays}
      />

      <ConfirmDialog
        open={!!dayToDelete}
        onOpenChange={(open) => !open && setDayToDelete(null)}
        title="Excluir dia"
        description={
          dayToDelete
            ? `O dia ${format(parseISO(dayToDelete.date), "dd/MM")} será excluído, junto com todas as pistas, aquecimentos, componentes e apresentações agendadas nele. Essa ação não pode ser desfeita.`
            : ""
        }
        confirmLabel="Excluir dia"
        confirmingLabel="Excluindo..."
        onConfirm={handleConfirmDeleteDay}
      />

      <ScheduleOverflowDialog
        open={!!overflow}
        newEndMinutes={overflow?.newEndMinutes ?? null}
        onExtend={handleExtendDayEnd}
        onCancel={handleCancelOverflow}
      />

      {/* Cobre a tela inteira (não só um indicador pequeno perto do
          toggle Linha do tempo/Tabela, que passava despercebido — pedido
          do usuário, 2026-08-05) enquanto soltar/mover/remover uma
          apresentação ainda não terminou de reconciliar no backend (ver
          `scheduleMutationPending`). `pointer-events-none` de propósito:
          é só feedback visual, não precisa bloquear clique — a ação já
          está em voo e o próximo refetch vai substituir o estado atual
          de qualquer forma. */}
      {scheduleMutationPending && (
        <div className="pointer-events-none fixed inset-0 z-50 flex items-center justify-center bg-background/70 backdrop-blur-sm">
          <div className="flex flex-col items-center gap-3">
            <Loader2 className="size-8 animate-spin text-primary" />
            <p className="text-sm font-medium text-foreground">Salvando alteração...</p>
          </div>
        </div>
      )}
    </div>
  );
}
