import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { format, parseISO } from "date-fns";
import { ArrowLeft, CalendarClock, Copy, GanttChartSquare, Sparkles, Table2 } from "lucide-react";
import {
  DndContext,
  PointerSensor,
  useSensor,
  useSensors,
  type DragEndEvent,
  type DragMoveEvent,
  type DragStartEvent,
} from "@dnd-kit/core";
import { AppSidebar } from "@/components/AppSidebar";
import { NotificationBell } from "@/components/NotificationBell";
import { Button } from "@/components/ui/button";
import { ScheduleDaySettingsBar } from "@/components/ScheduleDaySettingsBar";
import {
  ScheduleTimeline,
  SCHEDULE_PX_PER_MINUTE,
  RESOURCE_DRAG_PREFIX,
  RESOURCE_DROP_PREFIX,
} from "@/components/ScheduleTimeline";
import { ScheduleTableView, TABLE_CELL_PREFIX } from "@/components/ScheduleTableView";
import { UnscheduledTeamsPanel } from "@/components/UnscheduledTeamsPanel";
import { EventComponentsLibrary } from "@/components/EventComponentsLibrary";
import { AutoGenerateDialog } from "@/components/AutoGenerateDialog";
import { EditResourceDialog } from "@/components/EditResourceDialog";
import { CreateResourceDialog } from "@/components/CreateResourceDialog";
import { ScheduleSummaryFooter } from "@/components/ScheduleSummaryFooter";
import { ConfirmDialog } from "@/components/ConfirmDialog";
import { ScheduleOverflowDialog } from "@/components/ScheduleOverflowDialog";
import { findScheduleConflicts } from "@/lib/scheduleConflicts";
import { computeResourceTimes } from "@/lib/scheduleTime";
import {
  scheduleApi,
  usersApi,
  ApiError,
  type AutoGenerateSchedulePayload,
  type ScheduleDay,
  type ScheduleEntry,
  type UnscheduledPair,
  type UpdateScheduleDayPayload,
  type UserProfile,
} from "@/api/client";
import { useAuthStore } from "@/store/auth";

export function SchedulePage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const logout = useAuthStore((s) => s.logout);

  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [days, setDays] = useState<ScheduleDay[]>([]);
  const [selectedDayId, setSelectedDayId] = useState<string | null>(null);
  const [unscheduled, setUnscheduled] = useState<UnscheduledPair[]>([]);
  const [addingDay, setAddingDay] = useState(false);
  const [autoGenerateOpen, setAutoGenerateOpen] = useState(false);
  const [editingResourceId, setEditingResourceId] = useState<string | null>(null);
  const [createResourceOpen, setCreateResourceOpen] = useState(false);
  const [replicateOpen, setReplicateOpen] = useState(false);
  const [dayToDelete, setDayToDelete] = useState<ScheduleDay | null>(null);
  const [overflow, setOverflow] = useState<{
    dayId: string;
    newEndMinutes: number;
    undo: () => Promise<void>;
  } | null>(null);
  const [viewMode, setViewMode] = useState<"timeline" | "table">("timeline");
  const [error, setError] = useState<string | null>(null);
  const [activeDragEntryId, setActiveDragEntryId] = useState<string | null>(null);
  const [activeDragDelta, setActiveDragDelta] = useState({ x: 0, y: 0 });

  useEffect(() => {
    usersApi.me().then(setProfile).catch(() => setProfile(null));
  }, []);

  useEffect(() => {
    if (!id) return;
    refetchDays();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  // Equipes não agendadas é por dia (cada equipe/categoria pode se
  // apresentar uma vez em cada dia — ver ScheduleService), então
  // refaz o fetch sempre que o dia selecionado mudar, não só ao
  // montar a página.
  useEffect(() => {
    if (!id || !selectedDayId) return;
    refetchUnscheduled();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id, selectedDayId]);

  function refetchDays() {
    if (!id) return;
    scheduleApi
      .listDays(id)
      .then((loaded) => {
        setDays(loaded);
        setSelectedDayId((current) => current ?? loaded[0]?.id ?? null);
      })
      .catch(() => setError("Não foi possível carregar o cronograma. Tente novamente."));
  }

  function refetchUnscheduled() {
    if (!id || !selectedDayId) return;
    scheduleApi
      .getUnscheduled(id, selectedDayId)
      .then(setUnscheduled)
      .catch(() => setUnscheduled([]));
  }

  const selectedDay = days.find((d) => d.id === selectedDayId) ?? null;
  const conflicts = useMemo(
    () => (selectedDay ? findScheduleConflicts(selectedDay) : new Map<string, string[]>()),
    [selectedDay],
  );

  // Enquanto o usuário arrasta uma apresentação, o aquecimento
  // vinculado a ela (linkedEntryId) "anda junto" visualmente — só
  // efeito visual (ScheduleEntryCard/TableEntryCell espelham este
  // deslocamento no aquecimento), o reposicionamento de verdade
  // acontece no backend ao soltar (ver ScheduleService.moveEntry, que
  // agora recalcula o aquecimento junto quando a apresentação move).
  const peerDrag = useMemo(() => {
    if (!activeDragEntryId || !selectedDay) return null;
    const allEntries = selectedDay.resources.flatMap((r) => r.entries);
    const activeEntry = allEntries.find((e) => e.id === activeDragEntryId);
    if (!activeEntry || activeEntry.type !== "presentation") return null;
    // O intervalo "Aguardando aquecimento" também tem linkedEntryId
    // apontando pra esta apresentação (ver ScheduleService) — sem
    // filtrar por type, o find abaixo podia pegar esse intervalo em
    // vez do aquecimento de verdade.
    const warmup = allEntries.find(
      (e) => e.type === "warmup" && e.linkedEntryId === activeEntry.id,
    );
    if (!warmup) return null;
    return { entryId: warmup.id, x: activeDragDelta.x, y: activeDragDelta.y };
  }, [activeDragEntryId, activeDragDelta, selectedDay]);

  function handleDragStart(event: DragStartEvent) {
    setActiveDragEntryId(String(event.active.id));
    setActiveDragDelta({ x: 0, y: 0 });
  }

  function handleDragMove(event: DragMoveEvent) {
    setActiveDragDelta({ x: event.delta.x, y: event.delta.y });
  }

  function clearActiveDrag() {
    setActiveDragEntryId(null);
    setActiveDragDelta({ x: 0, y: 0 });
  }

  function handleLogout() {
    logout();
    navigate("/login");
  }

  async function handleAddDay() {
    if (!id) return;
    setAddingDay(true);
    try {
      const day = await scheduleApi.addDay(id);
      setDays((prev) => [...prev, day]);
      setSelectedDayId(day.id);
    } catch {
      setError("Não foi possível adicionar um novo dia.");
    } finally {
      setAddingDay(false);
    }
  }

  async function handleConfirmDeleteDay() {
    if (!id || !dayToDelete) return;
    await scheduleApi.removeDay(id, dayToDelete.id);
    // Se o dia excluído era o selecionado, limpa pra refetchDays cair
    // no primeiro dia restante (ver `current ?? loaded[0]?.id` ali).
    if (selectedDayId === dayToDelete.id) {
      setSelectedDayId(null);
    }
    refetchDays();
  }

  function handleUpdateDay(payload: UpdateScheduleDayPayload) {
    if (!id || !selectedDayId) return;
    scheduleApi
      .updateDay(id, selectedDayId, payload)
      .then((updated) => {
        setDays((prev) => prev.map((d) => (d.id === updated.id ? updated : d)));
      })
      .catch(() => setError("Não foi possível atualizar as configurações do dia."));
  }

  // Chamado depois de criar um item novo (apresentação, componente ou
  // intervalo personalizado) — o horário final de verdade só se sabe
  // depois que o backend já reconciliou aquecimentos/esperas (ver
  // ScheduleService.reconcileWarmupDelays/reconcileMatGaps), então o
  // recarregamento aqui já é o dado definitivo, não uma previsão.
  // Se algum recurso do dia passou do "Horário do dia" configurado,
  // guarda a ação de desfazer (`undo`) e abre o popup — o item já foi
  // criado no backend nesse ponto, só decide se ele fica (estendendo o
  // fim do dia) ou é removido de novo.
  async function checkDayOverflowAndMaybePrompt(dayId: string, undo: () => Promise<void>) {
    if (!id) return;
    const loaded = await scheduleApi.listDays(id);
    setDays(loaded);
    const day = loaded.find((d) => d.id === dayId);
    if (!day) return;
    const times = computeResourceTimes(day.resources, day.startMinutes);
    let maxEndMinutes = day.startMinutes;
    for (const t of times.values()) maxEndMinutes = Math.max(maxEndMinutes, t.endMinutes);
    if (maxEndMinutes > day.endMinutes) {
      setOverflow({ dayId, newEndMinutes: maxEndMinutes, undo });
    }
  }

  async function handleExtendDayEnd() {
    if (!id || !overflow) return;
    const updated = await scheduleApi.updateDay(id, overflow.dayId, {
      endMinutes: overflow.newEndMinutes,
    });
    setDays((prev) => prev.map((d) => (d.id === updated.id ? updated : d)));
    setOverflow(null);
  }

  async function handleCancelOverflow() {
    if (!overflow) return;
    await overflow.undo();
    setOverflow(null);
  }

  function handleRemoveEntry(entryId: string) {
    if (!id || !selectedDayId) return;
    scheduleApi
      .removeEntry(id, selectedDayId, entryId)
      .then(() => {
        refetchDays();
        refetchUnscheduled();
      })
      .catch(() => setError("Não foi possível remover este item do cronograma."));
  }

  async function handleAutoGenerate(payload: AutoGenerateSchedulePayload) {
    if (!id || !selectedDayId) return;
    const updated = await scheduleApi.autoGenerate(id, selectedDayId, payload);
    setDays((prev) => prev.map((d) => (d.id === updated.id ? updated : d)));
    refetchUnscheduled();
  }

  function handleCustomIntervalCreated(created: ScheduleEntry[]) {
    if (!id || !selectedDay) return;
    const dayId = selectedDay.id;
    const entry = created[0];
    checkDayOverflowAndMaybePrompt(dayId, async () => {
      if (entry) await scheduleApi.removeEntry(id, dayId, entry.id);
      refetchDays();
    });
  }

  async function handleReplicateToAllDays() {
    if (!id || !selectedDayId) return;
    const updated = await scheduleApi.replicateToAllDays(id, selectedDayId);
    setDays(updated);
    refetchUnscheduled();
  }

  function handleDragEnd(event: DragEndEvent) {
    clearActiveDrag();
    if (!id || !selectedDay) return;
    const { active, over } = event;
    if (!over) return;

    const activeIdRaw = String(active.id);
    const overIdRaw = String(over.id);

    // Reordenar as próprias linhas de recurso — arrastar o "handle"
    // (coluna esquerda) de um recurso sobre o de outro insere o
    // arrastado na posição do alvo (empurra os demais).
    if (activeIdRaw.startsWith(RESOURCE_DRAG_PREFIX)) {
      if (!overIdRaw.startsWith(RESOURCE_DROP_PREFIX)) return;
      const sourceResourceId = activeIdRaw.slice(RESOURCE_DRAG_PREFIX.length);
      const targetResourceId = overIdRaw.slice(RESOURCE_DROP_PREFIX.length);
      if (sourceResourceId === targetResourceId) return;

      const sortedResources = [...selectedDay.resources].sort((a, b) => a.order - b.order);
      const targetIndex = sortedResources.findIndex((r) => r.id === targetResourceId);
      if (targetIndex === -1) return;

      scheduleApi
        .moveResource(id, selectedDay.id, sourceResourceId, { order: targetIndex })
        .then(refetchDays)
        .catch(() => setError("Não foi possível reordenar este recurso."));
      return;
    }

    // A visão em tabela já solta direto num horário (o id do
    // droppable é "table-cell:<resourceId>:<rowStart>", ver
    // ScheduleTableView) — não precisa de conta de pixel nenhuma, só a
    // timeline calcula a posição a partir do deslocamento horizontal
    // do arrasto.
    let resourceId: string;
    let dropMinutes: number;
    if (overIdRaw.startsWith(TABLE_CELL_PREFIX)) {
      const rest = overIdRaw.slice(TABLE_CELL_PREFIX.length);
      const sepIndex = rest.lastIndexOf(":");
      resourceId = rest.slice(0, sepIndex);
      dropMinutes = Number(rest.slice(sepIndex + 1));
    } else {
      resourceId = overIdRaw;
      const overRect = over.rect;
      const activeRect = active.rect.current.translated;
      const dropX = activeRect ? activeRect.left - overRect.left : 0;
      dropMinutes = selectedDay.startMinutes + dropX / SCHEDULE_PX_PER_MINUTE;
    }

    const resource = selectedDay.resources.find((r) => r.id === resourceId);
    if (!resource) return;

    const times = computeResourceTimes(selectedDay.resources, selectedDay.startMinutes);
    const sortedEntries = [...resource.entries].sort((a, b) => a.order - b.order);
    let insertIndex = sortedEntries.length;
    for (let i = 0; i < sortedEntries.length; i++) {
      const t = times.get(sortedEntries[i].id);
      if (t && dropMinutes < (t.startMinutes + t.endMinutes) / 2) {
        insertIndex = i;
        break;
      }
    }

    if (activeIdRaw.startsWith("unscheduled:")) {
      const [, teamId, categoryId] = activeIdRaw.split(":");
      const dayId = selectedDay.id;
      scheduleApi
        .createEntry(id, dayId, {
          resourceId,
          type: "presentation",
          order: insertIndex,
          teamId,
          categoryId,
        })
        .then((created) => {
          refetchUnscheduled();
          const presentation = created.find((e) => e.type === "presentation");
          checkDayOverflowAndMaybePrompt(dayId, async () => {
            if (presentation) await scheduleApi.removeEntry(id, dayId, presentation.id);
            refetchDays();
            refetchUnscheduled();
          });
        })
        .catch((err) =>
          setError(
            err instanceof ApiError ? err.message : "Não foi possível agendar esta apresentação.",
          ),
        );
      return;
    }

    if (activeIdRaw.startsWith("component:")) {
      const [, type, durationStr, label] = activeIdRaw.split(":");
      const dayId = selectedDay.id;
      scheduleApi
        .createEntry(id, dayId, {
          resourceId,
          type: type as "break" | "ceremony" | "award",
          order: insertIndex,
          durationMinutes: Number(durationStr),
          label: label || undefined,
        })
        .then((created) => {
          const entry = created[0];
          checkDayOverflowAndMaybePrompt(dayId, async () => {
            if (entry) await scheduleApi.removeEntry(id, dayId, entry.id);
            refetchDays();
          });
        })
        .catch(() => setError("Não foi possível adicionar este componente."));
      return;
    }

    scheduleApi
      .moveEntry(id, selectedDay.id, activeIdRaw, { resourceId, order: insertIndex })
      .then(refetchDays)
      .catch(() => setError("Não foi possível mover este item."));
  }

  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }));

  return (
    <div className="flex h-svh bg-background">
      <AppSidebar profile={profile} onLogout={handleLogout} />

      <DndContext
        sensors={sensors}
        onDragStart={handleDragStart}
        onDragMove={handleDragMove}
        onDragEnd={handleDragEnd}
        onDragCancel={clearActiveDrag}
      >
        <main className="flex flex-1 flex-col overflow-y-auto">
          <div className="flex items-center justify-between px-10 pt-6">
            <button
              type="button"
              onClick={() => navigate(`/events/${id}/setup`)}
              className="flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
            >
              <ArrowLeft className="size-4" />
              Voltar para configuração do evento
            </button>
            <NotificationBell />
          </div>

          <div className="flex min-h-0 flex-1 flex-col gap-6 px-10 pb-10">
            {error && <p className="mt-6 text-sm text-destructive">{error}</p>}

            <div className="mt-6 flex flex-wrap items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground">
                  <CalendarClock className="size-5" />
                </div>
                <div>
                  <h1 className="text-2xl font-semibold text-foreground">Cronograma do Evento</h1>
                  <p className="mt-1 text-sm text-muted-foreground">
                    Planeje a utilização dos recursos do dia (pistas, aquecimentos e outros).
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                {days.length > 1 && (
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setReplicateOpen(true)}
                    disabled={!selectedDay}
                  >
                    <Copy className="size-4" />
                    Repetir em todos os dias
                  </Button>
                )}
                <Button type="button" onClick={() => setAutoGenerateOpen(true)} disabled={!selectedDay}>
                  <Sparkles className="size-4" />
                  Gerar automaticamente
                </Button>
              </div>
            </div>

            {selectedDay && (
              <>
                <ScheduleDaySettingsBar
                  days={days}
                  day={selectedDay}
                  onSelectDay={setSelectedDayId}
                  onAddDay={handleAddDay}
                  addingDay={addingDay}
                  onUpdate={handleUpdateDay}
                  onDeleteDay={(dayId) =>
                    setDayToDelete(days.find((d) => d.id === dayId) ?? null)
                  }
                />

                <div className="grid min-h-0 flex-1 grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
                  <div className="flex min-h-0 min-w-0 flex-col gap-6">
                    <div className="flex items-center gap-1 self-start rounded-lg border border-border/60 bg-muted/30 p-1">
                      <Button
                        type="button"
                        size="sm"
                        variant={viewMode === "timeline" ? "default" : "ghost"}
                        onClick={() => setViewMode("timeline")}
                      >
                        <GanttChartSquare className="size-4" />
                        Linha do tempo
                      </Button>
                      <Button
                        type="button"
                        size="sm"
                        variant={viewMode === "table" ? "default" : "ghost"}
                        onClick={() => setViewMode("table")}
                      >
                        <Table2 className="size-4" />
                        Tabela
                      </Button>
                    </div>
                    {viewMode === "timeline" ? (
                      <ScheduleTimeline
                        day={selectedDay}
                        conflicts={conflicts}
                        onRemoveEntry={handleRemoveEntry}
                        onAddResource={() => setCreateResourceOpen(true)}
                        onEditResource={setEditingResourceId}
                        peerDrag={peerDrag}
                      />
                    ) : (
                      <ScheduleTableView
                        day={selectedDay}
                        conflicts={conflicts}
                        onRemoveEntry={handleRemoveEntry}
                        peerDrag={peerDrag}
                      />
                    )}
                    <ScheduleSummaryFooter day={selectedDay} />
                  </div>
                  <div className="flex flex-col gap-6 overflow-y-auto">
                    <UnscheduledTeamsPanel
                      pairs={unscheduled}
                      ignoreUnscheduled={selectedDay.ignoreUnscheduledPresentations}
                      onToggleIgnoreUnscheduled={(value) =>
                        handleUpdateDay({ ignoreUnscheduledPresentations: value })
                      }
                    />
                    <EventComponentsLibrary
                      eventId={id!}
                      day={selectedDay}
                      onCreated={handleCustomIntervalCreated}
                    />
                  </div>
                </div>
              </>
            )}
          </div>
        </main>
      </DndContext>

      <AutoGenerateDialog
        open={autoGenerateOpen}
        onOpenChange={setAutoGenerateOpen}
        onGenerate={handleAutoGenerate}
      />

      {id && selectedDay && (
        <EditResourceDialog
          eventId={id}
          dayId={selectedDay.id}
          resourceId={editingResourceId}
          allResources={selectedDay.resources}
          onOpenChange={(open) => !open && setEditingResourceId(null)}
          onChanged={refetchDays}
        />
      )}

      {id && selectedDay && (
        <CreateResourceDialog
          eventId={id}
          dayId={selectedDay.id}
          existingResources={selectedDay.resources}
          open={createResourceOpen}
          onOpenChange={setCreateResourceOpen}
          onCreated={refetchDays}
        />
      )}

      <ConfirmDialog
        open={replicateOpen}
        onOpenChange={setReplicateOpen}
        title="Repetir cronograma em todos os dias"
        description="O horário do dia (início/fim, tempo de aquecimento), as pistas, aquecimentos, componentes (Almoço, Abertura, Premiação, Contestação de notas, intervalos personalizados) e as apresentações/aquecimentos das equipes do dia selecionado serão copiados para todos os outros dias do evento — substituindo completamente o que já existir neles."
        confirmLabel="Repetir mesmo assim"
        confirmingLabel="Repetindo..."
        onConfirm={handleReplicateToAllDays}
      />

      <ConfirmDialog
        open={!!dayToDelete}
        onOpenChange={(open) => !open && setDayToDelete(null)}
        title="Excluir dia"
        description={
          dayToDelete
            ? `O dia ${format(parseISO(dayToDelete.date), "dd/MM")} será excluído, junto com todas as pistas, aquecimentos, componentes e apresentações agendadas nele. Essa ação não pode ser desfeita.`
            : ""
        }
        confirmLabel="Excluir dia"
        confirmingLabel="Excluindo..."
        onConfirm={handleConfirmDeleteDay}
      />

      <ScheduleOverflowDialog
        open={!!overflow}
        newEndMinutes={overflow?.newEndMinutes ?? null}
        onExtend={handleExtendDayEnd}
        onCancel={handleCancelOverflow}
      />
    </div>
  );
}
